[tool.poetry]
name = "weav"
version = "0.1.0"
description = "extract URLs, strings, and more from JavaScript code"
authors = ["Shuaib Oladigbolu <shuaib@footstep.ninja>"]
license = "AGPL-3.0-only"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
bs4 = "^0.0.2"
argparse = "^1.4.0"
tree-sitter = "^0.22.3"
tree-sitter-javascript = "^0.21.4"

[tool.poetry.scripts]
weav = "weav.weav:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
